runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /static/(.*)
    static_files: build/static/\1
    upload: build/static/(.*)
  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico
  - url: /(.*)?
    static_files: build/index.html
    upload: build/index.html
